### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by rsainiRicky** [pay2all/pay2all-recharge-api-document#2]
Failed to load https://www.pay2all.in/web-api/get-provider?api_token=1swdyd5JddEUDK8iqwZJpMmCTPzakBemqOIAwV00f1O9x0LDG5hQjtb98brW: **The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://localhost:4200' is therefore not allowed access.**
app.component.ts:18 
HttpErrorResponse error:ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}
headers:HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
message:"Http failure response for (unknown url): 0 Unknown Error"
name:"HttpErrorResponse"
ok:false
status:0
statusText:"Unknown Error"
url:null
__proto__:HttpResponseBase

**Comment by pay2all** [comment]
'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,

**Comment by rsainiRicky** [comment]
Hi, 
I am still getting the same issue 
![image](https://user-images.githubusercontent.com/33736129/33525113-cf2d674a-d84e-11e7-8e29-a26047d4879a.png)

**Comment by sanjaylive** [comment]
Solved
